version: '3'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6381:6379
    volumes:
      - /Users/caodinhsyvy/DATA/CapstoneProject/redisData/dataEverywhere:/data

  api:
    build:
      context: .
    image: data_everywhere_image
    network_mode: host
    command: [
      "java",
      "-jar",
      "-Dspring.config.name=application",
      "-Dspring.config.location=file:application.properties",
      "app.jar"
    ]